### ISSUE TITLE
Suggest a better UI

### ISSUE THREAD

**Issue by deprov447** [deprov447/FakeFeed#1]
## Issue:
Currently the UI looks like this :
![Fakefeed](https://i.imgur.com/tQnm27c.png)
which is obviously not a very good design. The linear button flow makes it look like a script when a lot of customization options are there/can be added.

## Resolution:
Please propose a better and intuitive design. You can create a mockup using any of the tools available and share your designs here.

**Comment by william-monroy** [comment]
Hi @deprov447, I would like to work on this issue. Could you tell me more about the project so I can take it into account when making my proposal?

**Comment by deprov447** [comment]
Hey @william-monroy 
So FakeFeed is a linux specific application to change the original web cam feed to something else (currently it supports only streaming a video file, but progress on the way)

Please read [this](https://github.com/deprov447/FakeFeed/blob/master/README.md) for more detail.

**Comment by william-monroy** [comment]
Hi @deprov447, I like the idea, could you assign this topic to me?
